### ISSUE TITLE
`KroneckerSample` problems

### ISSUE THREAD

**Issue by ParadaCarleton** [SciML/QuasiMonteCarlo.jl#34]
I can't work out how `KroneckerSample` is supposed to work. I'm not sure whether this is because the docstring is extremely unclear, or if the code is actually broken.

**Comment by ChrisRackauckas** [comment]
From https://github.com/SciML/QuasiMonteCarlo.jl/pull/20  https://github.com/SciML/Surrogates.jl/pull/125 @ludoro what was the reference for this one?

**Comment by ParadaCarleton** [comment]
@ChrisRackauckas from what I can tell the code is just completely broken/incorrect. The package might need a lot of rewriting :sweat_smile:

**Comment by ChrisRackauckas** [comment]
It does. And this time around, a lot more adding of references to the docstrings.
