### ISSUE TITLE
`GoldenSample` Incorrect

### ISSUE THREAD

**Issue by ParadaCarleton** [SciML/QuasiMonteCarlo.jl#36]
I compared the results here to those given by GoldenSequences.jl, and the implementation here looks wrong. It looks like the mistake is that each is based on `φ[i]^i` for `i in 1:d`, rather than powers of the same ratio `φ[d]^i` (as they should be).

**Comment by ChrisRackauckas** [comment]
Thanks, can you PR the fix and include a source? The lineage here seems to be https://github.com/SciML/Surrogates.jl/pull/126 and https://github.com/SciML/QuasiMonteCarlo.jl/pull/20, but there's no source. So it would be good to have that in the docstring.

**Comment by ParadaCarleton** [comment]
> Thanks, can you PR the fix and include a source? The lineage here seems to be [SciML/Surrogates.jl#126](https://github.com/SciML/Surrogates.jl/pull/126) and #20, but there's no source. So it would be good to have that in the docstring.

I can definitely add a source for using them in 1 or 2 dimensions, but there seem to be no references establishing the adequacy of these sequences in more than 2 dimensions, apart from a single blog post by a non-mathematician which contains no formal proofs.

There is, however, literature on using them in either 1 or 2 dimensions, where they're conjectured to have optimal properties. It's not at all clear the generalization in the blog post has these properties, and the sequences also appear to have exceedingly poor 2d projections. Here it is struggling with 8 dimensions and 64 points:
![image](https://user-images.githubusercontent.com/71727937/193968705-cd91e598-abc5-4cc9-aa65-a886dc2527e3.png)
While Sobol has very little trouble:
![image](https://user-images.githubusercontent.com/71727937/193968833-05d2fc39-8248-498d-b1f2-7a06b4a79f4d.png)

**Comment by ChrisRackauckas** [comment]
Can you paste the links to these blog posts and such? This library needs to capture more of this kind of information in the docstrings (for all of the sampling methods 😅)

**Comment by ParadaCarleton** [comment]
In an extremely funny turn of events I have since learned about component-by-component constructions for QMC lattices. The original, buggy code probably produced better samples than the new "correct" code that follows the method laid out [here](https://extremelearning.com.au/unreasonable-effectiveness-of-quasirandom-sequences/).
