### ISSUE TITLE
Remove `Distributions` from dependencies

### ISSUE THREAD

**Issue by ParadaCarleton** [SciML/QuasiMonteCarlo.jl#62]
OK, so I originally thought `Distributions` was here so you could use QMC sequences to sample from a distribution, but apparently that just doesn't work.
```
julia> import QuasiMonteCarlo as QMC

julia> using Distributions

julia> QMC.sample(1024, zeros(10), ones(10), SobolSample(), Normal())
ERROR: MethodError: no method matching sample(::Int64, ::Vector{Float64}, ::Vector{Float64}, ::SobolSample, ::Normal{Float64})
Closest candidates are:
  sample(::Integer, ::Union{Number, Tuple, AbstractVector}, ::Union{Number, Tuple, AbstractVector}, ::SobolSample) at ~/.julia/packages/QuasiMonteCarlo/iBmQ6/src/QuasiMonteCarlo.jl:205
  sample(::Integer, ::Union{Number, Tuple, AbstractVector}, ::Union{Number, Tuple, AbstractVector}, ::QuasiMonteCarlo.SamplingAlgorithm) at ~/.julia/packages/QuasiMonteCarlo/iBmQ6/src/QuasiMonteCarlo.jl:146
  sample(::Integer, ::Union{Number, Tuple, AbstractVector}, ::Union{Number, Tuple, AbstractVector}, ::FaureSample) at ~/.julia/packages/QuasiMonteCarlo/iBmQ6/src/Faure.jl:45
  ...
```
Is there any reason to keep `Distributions` hanging around, or should we just remove the dependency?

**Comment by ChrisRackauckas** [comment]
`QMC.sample(1024, 1 Normal())` should work. We should split Distributions to have a DistributionsBase since we only need the abstract type.

**Comment by ParadaCarleton** [comment]
> `QMC.sample(1024, 1 Normal())` should work. We should split Distributions to have a DistributionsBase since we only need the abstract type.

Right, so I know `QMC.sample(1024, 1, Normal())` works, but I don't think QMC is adding anything here--you might as well just call `rand(Normal(), 1024)`.

**Comment by ChrisRackauckas** [comment]
It simplifies interface construction, because then something that supports `sample` also supports random sampling from distributions. It's about how it can be used from within packages.

**Comment by ParadaCarleton** [comment]
> It simplifies interface construction, because then something that supports `sample` also supports random sampling from distributions. It's about how it can be used from within packages.

I think that would make sense if we supported a single interface for sampling from both uniform and non-uniform distributions, but from what I can tell we don't; I'm also not sure what package would need to use the same interface for both QMC points on the unit square and IID points on a completely different space.

One thing we could do instead is allow passing a transformation that can be applied to all the points, e.g. a coordinatewise inverse-cdf transform. That could be useful for both QMC and MC points.

**Comment by ChrisRackauckas** [comment]
> but wouldn't require Distributions (as users can pass the CDF itself).

I wouldn't expect most users to know or define the CDF. Distributions.jl and Measurements.jl are pretty standard tools for this. If anything, we can just make them weak dependencies.

**Comment by ChrisRackauckas** [comment]
Done https://github.com/SciML/QuasiMonteCarlo.jl/pull/86

**Comment by ChrisRackauckas** [comment]
I'm considering this non-breaking since in order to actually use it, you needed to `using Distributions` to get the distributions to pass in anyways, so making it an extension doesn't have a material change to any code that isn't doing something funky like `QuasiMonteCarlo.Distributions. ...`
