### ISSUE TITLE
Halton Sample not defined

### ISSUE THREAD

**Issue by fabrizioleone** [SciML/QuasiMonteCarlo.jl#76]
Hi, 

Thanks for this great package. 

It looks like I can't use HaltonSample. If I run your example code

```Julia
using QuasiMonteCarlo, Distributions
lb = [0.1,-0.5]
ub = [1.0,20.0]
n = 5
d = 2
s = QuasiMonteCarlo.sample(n,lb,ub,HaltonSample([10,3], false))
```

I get the following error: ```UndefVarError: HaltonSample not defined```. Is this a known problem or am I missing something?

Thanks

**Comment by ParadaCarleton** [comment]
@ChrisRackauckas did we ever make the changes we needed for Surrogates.jl to work? If so can we bump the version?

**Comment by ChrisRackauckas** [comment]
No not yet. It's haunting me.

**Comment by ChrisRackauckas** [comment]
It's released, so I'll close this. But surrogates still needs an update and we're tracking that separately.
