### ISSUE TITLE
Error in sample() usage

### ISSUE THREAD

**Issue by banachtech** [SciML/QuasiMonteCarlo.jl#80]
Documentation says this method signature should work.
```
julia> using QuasiMonteCarlo
julia> d, n = 4, 2^15
(4, 32768)
julia> Z = QuasiMonteCarlo.sample(n, d, SobolSample());
ERROR: MethodError: no method matching sample(::Int64, ::Int64, ::SobolSample)

Closest candidates are:
  sample(::Integer, ::Union{Number, Tuple, AbstractVector}, ::Union{Number, Tuple, AbstractVector}, ::FaureSample)
  ...
```

**Comment by dmetivie** [comment]
The `README.md` matches the soon-to-be (when??) released version, see issue #76 .
See [see the stable documentation](https://docs.sciml.ai/QuasiMonteCarlo/stable/) for current version.
If you want the next release features, I think you can do
```julia
pkg> add QuasiMonteCarlo#master
```
and look at [in-development documentation](https://docs.sciml.ai/QuasiMonteCarlo/dev/).

**Comment by banachtech** [comment]
I see, thanks!

**Comment by ChrisRackauckas** [comment]
It should be tagged now.
