### ISSUE TITLE
Incorrect Halton Sequence

### ISSUE THREAD

**Issue by FriesischScott** [SciML/QuasiMonteCarlo.jl#83]
In `v0.3` the numbers returned by the `HaltonSample()` changed and I believe are now incorrect.

The first 4 points in `d = 2` used to return (in `v0.2`)
```
julia> s = QuasiMonteCarlo.sample(4, zeros(2), ones(2), LowDiscrepancySample([2, 3], false))
2×4 Matrix{Float64}:
 0.5       0.25      0.75      0.125
 0.333333  0.666667  0.111111  0.444444
 ```
which are the correct four points for the Halton Sequences in `d=2` with bases `[2, 3]`.

In the new version, the bases are internally selected  with `bases = nextprimes(one(n), d)` which returns `[2, 3]`  for two dimensions. 

However, the points returned are entirely different and the sequence changes based on the number of samples requested like
```
julia> s = QuasiMonteCarlo.sample(4, 2, HaltonSample())
2×4 Matrix{Float64}:
 0.125  0.625     0.375     0.875
 0.125  0.458333  0.791667  0.236111
```
and
```
julia> s = QuasiMonteCarlo.sample(5, 2, HaltonSample())
2×5 Matrix{Float64}:
 0.1  0.6       0.35      0.85      0.225
 0.1  0.433333  0.766667  0.211111  0.544444
```

**Comment by ParadaCarleton** [comment]
> which are the correct four points for the Halton Sequences in `d=2` with bases `[2, 3]`

While a common mistake, these are not the correct 4 points. The Halton sequence only guarantees that the first `2^n` points in the first dimension are evenly spaced, with one in each of the first `2^n` boxes--`[0, 0.25), [0.25, 0.5), [0.5, 0.75), [0.75, 1)`--and similarly for additional dimensions. Which 4 points are used is up to convention. The left-aligned points go `0, 0.5, 0.75...` whereas centered points go `0.25, 0.75, 0.125...` as seen in the example where you chose 4 points.

The sequence you cited, however, makes a common mistake of using the left-aligned points, but then excluding the 0th point. `0.5, 0.25, 0.75, 0.125` fails the equal spacing test, as the distance from `0.125` to `0.25` is shorter than all the other distances.

In this case, the choice made is to space all points as evenly as possible without breaking the stratification properties, meaning you get results like the ones here. However, we really do recommend scrambling points, in which case minor placement details like these don't matter.

**Comment by FriesischScott** [comment]
Thanks for the clarification. Do you perhaps have a reference for this? In every publication I can find the unscrambled Halton sequence is a generalized van der corbut sequence for higher dimensions and has a specific definition (granted it does start at 0) based on the radical inverse function. A very crude implementation like this
```julia
function φ(x::Integer, base::Integer)
    b = parse.(Int, reverse(split(string(x; base=base), "")))
    p = [base^pᵢ for pᵢ in 1:length(b)]
    return sum(b ./ p)
end
```
would return the same points in order regardless of the number of points I chose.

I can't find any reference to the points used being up to convention.

**Comment by FriesischScott** [comment]
It seems your implementation converges to the Halton Sequence with increasing number of samples.

8 Samples
![halton-1](https://github.com/SciML/QuasiMonteCarlo.jl/assets/6382176/df92ab0f-d696-45b6-bafe-e541cb30a42b)
32 Samples
![halton-2](https://github.com/SciML/QuasiMonteCarlo.jl/assets/6382176/08466ea4-26b0-4a96-b8ec-b62b563cfa7e)
1024 Samples
![halton-3](https://github.com/SciML/QuasiMonteCarlo.jl/assets/6382176/ef23a530-3ce6-4182-acc5-ff91249bbec1)

With 1024 points the difference is down to around 5e-4 in each dimension.

I'm happy to be proven wrong, but to me this doesn't seem correct.

**Comment by ParadaCarleton** [comment]
> Thanks for the clarification. Do you perhaps have a reference for this?

The relevant search term is "(t, s) sequences." In short, any slight perturbation of the Halton points (or any net) maintains the same stratification properties, so there's no reason to prefer one to another (they're all equally well-separated).

The only exception is that if the first point is `0, 0, 0...`, this often causes errors, because taking an inverse-probability transform will usually map the point at `0` to `-inf`. The points provided by QuasiMonteCarlo.jl are slightly perturbed (by `1/2n`) to avoid this bug, while still maintaining the correct stratification properties. (The perturbation can't push any point by more than `1/n` without shifting points between strata.)

**Comment by FriesischScott** [comment]
Thanks!
