### ISSUE TITLE
GridSample appears to sample on a line

### ISSUE THREAD

**Issue by frankier** [SciML/QuasiMonteCarlo.jl#93]
It looks like GridSample is generating points in a line. I would expect the points to form a grid.

```
> using QuasiMonteCarlo
> QuasiMonteCarlo.sample(5, [-6.0, -6.0], [6.0, 6.0], GridSample())
2×5 Matrix{Float64}:
 -4.8  -2.4  0.0  2.4  4.8
 -4.8  -2.4  0.0  2.4  4.8
```

**Comment by ChrisRackauckas** [comment]
Solved and tested better in https://github.com/SciML/QuasiMonteCarlo.jl/pull/94. It was somewhat ill-defined what it's behavior truly was, so that was clarified as well:

> A simple rectangular grid lattice. Samples `n` random samples from a grid with `dx = (ub -lb)/n``
