### ISSUE TITLE
Randomized Halton sequence?

### ISSUE THREAD

**Issue by FriesischScott** [SciML/QuasiMonteCarlo.jl#99]
**Question❓**

The documentation states that the base for scrambling should match the base of the sequence.

> In principle, the base b used for scrambling methods ScramblingMethods(b, pad, rng) can be an arbitrary integer. However, to preserve good Quasi Monte Carlo properties, it must match the base of the sequence to scramble.

How does this relate to the Halton sequence, where the next `d` primes are used as bases? Are the randomizations applicable here? If so, which base would yield the best results? 

What is the base of the `LatticeRule`? 2?

**Comment by dmetivie** [comment]
It is an imprecision in the doc (that I should clarify):
this advice only makes sense for digital net (also called (t,m,s)-net) in base `b`.
Scrambling methods are made for these types of QMC sequences. Lattice sequences are not digital net. Neither are Halton (though they "resemble" more digital net than Lattice). Hence, there are no guarantees scrambling Halton/Lattice will produce better results than the unscrambled version.

I recommend this paper [A randomized Halton algorithm in R](https://arxiv.org/pdf/1706.02808.pdf) by A. Owen exactly on this topic.
The method proposed there is not yet implemented in QuasiMonteCarlo.jl but it should! Feel free to do it (I lack time these days)!
It is also some kind of scrambling I believe but adapted to Halton.

Last thing: contrary to other QMC packages, here one can choose randomization methods independently of the QMC sequence.
This is great in principle, but can lead to misuse (#TODO clarify the doc). Keep in mind the following:
- For Lattice, the most appropriate randomization is Shift aka Cranley-Patterson rotation (I believe there exists better algo but not implemented yet)
- For digital nets e.g. Sobol, Faure the best is to use Linear Matrix Scrambling aka Matousek scramble or Nested Uniform Scrambling aka Owen Scrambling (the latter is supposed to be better but more energy consuming).
- Halton: see paper above
- etc.

**Comment by FriesischScott** [comment]
Thank you for the clarification. I'll see if we can contribute the randomization technique for Halton outlined in the paper.
